version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: GbPFWrC6N2umbZxa
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - mybus-compose-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    volumes:
      - ./mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: GbPFWrC6N2umbZxa
    links:
      - mongo
    networks:
      - mybus-compose-network
  server:
    build: 
      context: ./server
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: GbPFWrC6N2umbZxa
      MONGO_SERVER: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: mybusway
      WAIT_HOSTS: mongo:27017
      WAIT_HOSTS_TIMEOUT: 300
      WAIT_SLEEP_INTERVAL: 30
      WAIT_HOST_CONNECT_TIMEOUT: 30
    ports: 
      - "8080:8080"
    container_name: mybusway-server
    depends_on:
      - mongo
    env_file:
      - ./.env.local
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - mybus-compose-network
    command: sh -c "/wait && node src/index.js"
  client: 
    build:
      context: ./client
      args:
        REACT_APP_MYBUSWAY_SERVER: "http://localhost:8080"
    container_name: mybusway-client
    depends_on:
      - server
    restart: "no"
    volumes:
      - ./client:/app
      - /app/node_modules
    ports: 
      - "80:80"
    networks:
      - mybus-compose-network
  postgres: 
    image: postgres:alpine
    container_name: postgres
    ports: 
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: hTcDUVse5E9ZDB5g
      POSTGRES_USER: keycloak
      POSTGRES_DB: keycloak
    networks:
      - mybus-compose-network
  keycloak:
    image: jboss/keycloak
    container_name: keycloak 
    ports: 
      - "5400:8080"
    environment: 
      KEYCLOAK_USER: admin 
      KEYCLOAK_PASSWORD: NMdy4dkra9JzpeNP
      DB_VENDOR: postgres
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: hTcDUVse5E9ZDB5g
    networks:
      - mybus-compose-network
          
networks: 
    mybus-compose-network:
      driver: bridge