version: "3.8"
services:
  server:
    build: 
      context: ./server
    ports: 
      - "8080:8080"
    container_name: mybusway-server
    env_file:
      - ./.env.local
    volumes:
      - ./server:/app
      - /app/node_modules
  client: 
    build:
      context: ./client
      args:
        REACT_APP_MYBUSWAY_SERVER: "http://localhost:8080"
    container_name: mybusway-client
    depends_on:
      - server
    restart: "no"
    volumes:
      - ./client:/app
      - /app/node_modules
    ports: 
      - "80:80"

