version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: GbPFWrC6N2umbZxa
    ports:
      - "27017:27017"
    volumes:
      - ./data/db:/data/db
    networks:
      - mybus-compose-network
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: mongo
      ME_CONFIG_BASICAUTH_PASSWORD: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: GbPFWrC6N2umbZxa
    links:
      - mongo
    networks:
      - mybus-compose-network
  client: 
    build:
      context: ./client
      args:
        REACT_APP_MYBUSWAY_SERVER: "http://localhost:8080"
    container_name: mybusway-client
    restart: "no"
    volumes:
      - ./client:/app
      - /app/node_modules
    ports: 
      - "80:80"
    networks:
      - mybus-compose-network

networks: 
    mybus-compose-network:
      driver: bridge